export const STATUS = {
    SUCCESS: 200,
};
export const GENDER = {
    MALE: 0,
    FEMALE: 1,
    OTHER: 2,
};
export const TEAM = {
    FE: 1,
    BE: 2,
    TESTER: 3,
};
export const STATUS_EMPLOYEE = {
    SUBMIT_FILE_SAVE: "0",
    NEW_SAVE: "1",
    PENDING: "2",
    BEEN_APPEOVED: "3",
    ADDITIONAL_REQUIREMENTS: "4",
    REJECT: "5",
    PROFILE_END_REQUEST: "6",
    ACCEPT_REQUEST_END_PROFILE: "7",
    ADDITIONAL_REQUIREMENTS_END_PROFILE: "8",
    REJECT_REQUEST_END_PROFILE: "9",
};
export const STATUS_EMPLOYEE_NUMBER = {
    SUBMIT_FILE_SAVE: 0,
    NEW_SAVE: 1,
    PENDING: 2,
    BEEN_APPEOVED: 3,
    ADDITIONAL_REQUIREMENTS: 4,
    REJECT: 5,
    PROFILE_END_REQUEST: 6,
    ACCEPT_REQUEST_END_PROFILE: 7,
    ADDITIONAL_REQUIREMENTS_END_PROFILE: 8,
    REJECT_REQUEST_END_PROFILE: 9,
};
export const RELATIONSHIP = {
    CHILD: 1,
    PARENTS: 2,
    SIBLINGS: 3,
};
export const ROLE = {
    USER: 4,
    ADMIN: 3,
    MANAGE: 5,
};

export const TYPE_UPDATEHAPPENING = {
    SALARY: "SALARY",
    PROCESS: "PROCESS",
    RECOMMEND: "RECOMMEND",
};
export const TYPE_WAITING = {
    PROPOSE: "PROPOSE",
    PROMOTE: "PROMOTE",
    INCREASESALARY: "INCREASESALARY",
    RESUME: "RESUME",
};
export const TYPE_PROCESS = 2;

export const ACTIVE_KEY = "1";
